# PR labeler configuration file
ci:
- any: ['.github/**/*','!.github/ISSUE_TEMPLATE/*','!.github/PULL_REQUEST_TEMPLATE/*']
- ci/**/*
- .pre-commit-config.yaml
- .gitignore

github_actions:
- any: ['.github/**/*','!.github/ISSUE_TEMPLATE/*','!.github/PULL_REQUEST_TEMPLATE/*']

tests:
- any: ['tests/**/*']

documentation:
- docs/**/*
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
- .github/ISSUE_TEMPLATE/**/*
- .github/PULL_REQUEST_TEMPLATE/**/*
